extensions:
  basicauth:
    client_auth:
      username: admin
      password: admin

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/data-prepper:
    endpoint: "http://data-prepper:21892"
    tls:
      insecure: true

service:
  extensions: [basicauth]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus, otlp/data-prepper]
